"""empty message

Revision ID: 8c1731b38fcc
Revises: 20f40521d27a
Create Date: 2024-10-22 12:53:12.478782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1731b38fcc'
down_revision = '20f40521d27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_job_id'))
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
