"""empty message

Revision ID: 9df01e0d719c
Revises: 8c1731b38fcc
Create Date: 2024-10-22 13:09:07.736129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df01e0d719c'
down_revision = '8c1731b38fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('output')

    # ### end Alembic commands ###
