"""empty message

Revision ID: c25ab773d9c7
Revises: 9df01e0d719c
Create Date: 2024-10-26 16:41:53.255605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25ab773d9c7'
down_revision = '9df01e0d719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_job_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_session_id'))
        batch_op.drop_column('session_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
