"""empty message

Revision ID: d05661791578
Revises: d22f31926c22
Create Date: 2024-11-03 17:24:00.007404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05661791578'
down_revision = 'd22f31926c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_id', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_instance_id'), ['instance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_instance_id'))
        batch_op.drop_column('instance_id')

    # ### end Alembic commands ###
