"""empty message

Revision ID: d22f31926c22
Revises: f3bf95cd0e0b
Create Date: 2024-11-03 15:13:54.877766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22f31926c22'
down_revision = 'f3bf95cd0e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ec2_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.Column('ip_addr', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ec2_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ec2_instance_instance_id'), ['instance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ec2_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ec2_instance_instance_id'))

    op.drop_table('ec2_instance')
    # ### end Alembic commands ###
