"""empty message

Revision ID: f054143499ad
Revises: c25ab773d9c7
Create Date: 2024-10-26 17:24:14.255649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f054143499ad'
down_revision = 'c25ab773d9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_start_process', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('process_host', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('process_id', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('process_id')
        batch_op.drop_column('process_host')
        batch_op.drop_column('time_start_process')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
